#!/bin/bash
set +e

import_article() {
  local slug="$1"
  local title="$2"
  if [ -f "pages/${slug}.page" ]; then
    echo "skip: $slug"
    return
  fi
  echo "import: $slug"
  echo "(title: \"${title}\")" > "pages/${slug}.page"
  if ! pg-import "https://paulgraham.com/${slug}.html" >> "pages/${slug}.page"; then
    echo "ERROR: $slug" >&2
    rm -f "pages/${slug}.page"
  fi
}

import_article field "The Shape of the Essay Field"
import_article goodwriting "Good Writing"
import_article do "What to Do"
import_article woke "The Origins of Wokeness"
import_article writes "Writes and Write-Nots"
import_article when "When To Do What You Love"
import_article foundermode "Founder Mode"
import_article persistence "The Right Kind of Stubborn"
import_article getideas "How to Get New Ideas"
import_article read "The Need to Read"
import_article alien "Alien Truth"
import_article users "What I've Learned from Users"
import_article words "Putting Ideas into Words"
import_article goodtaste "Is There Such a Thing as Good Taste?"
import_article smart "Beyond Smart"
import_article weird "Weird Languages"
import_article hwh "How to Work Hard"
import_article own "A Project of One's Own"
import_article fn "Fierce Nerds"
import_article newideas "Crazy New Ideas"
import_article nft "An NFT That Saves Lives"
import_article real "The Real Reason to End the Death Penalty"
import_article richnow "How People Get Rich Now"
import_article simply "Write Simply"
import_article donate "Donate Unrestricted"
import_article worked "What I Worked On"
import_article earnest "Earnestness"
import_article ace "Billionaires Build"
import_article airbnbs "The Airbnbs"
import_article think "How to Think for Yourself"
import_article early "Early Work"
import_article wtax "Modeling a Wealth Tax"
import_article conformism "The Four Quadrants of Conformism"
import_article orth "Orthodox Privilege"
import_article cred "Coronavirus and Credibility"
import_article useful "How to Write Usefully"
import_article noob "Being a Noob"
import_article fh "Haters"
import_article mod "The Two Kinds of Moderate"
import_article fp "Fashionable Problems"
import_article lesson "The Lesson to Unlearn"
import_article nov "Novelty and Heresy"
import_article genius "The Bus Ticket Theory of Genius"
import_article sun "General and Surprising"
import_article pow "Charisma / Power"
import_article disc "The Risk of Discovery"
import_article pgh "How to Make Pittsburgh a Startup Hub"
import_article vb "Life is Short"
import_article ineq "Economic Inequality"
import_article re "The Refragmentation"
import_article jessica "Jessica Livingston"
import_article bias "A Way to Detect Bias"
import_article talk "Write Like You Talk"
import_article aord "Default Alive or Default Dead?"
import_article safe "Why It's Safe for Founders to Be Nice"
import_article name "Change Your Name"
import_article altair "What Microsoft Is this the Altair Basic of?"
import_article ronco "The Ronco Principle"
import_article work "What Doesn't Seem Like Work?"
import_article corpdev "Don't Talk to Corp Dev"
import_article 95 "Let the Other 95% of Great Programmers In"
import_article ecw "How to Be an Expert in a Changing World"
import_article know "How You Know"
import_article pinch "The Fatal Pinch"
import_article mean "Mean People Fail"
import_article before "Before the Startup"
import_article fr "How to Raise Money"
import_article herd "Investor Herd Dynamics"
import_article convince "How to Convince Investors"
import_article ds "Do Things that Don't Scale"
import_article invtrend "Startup Investing Trends"
import_article startupideas "How to Get Startup Ideas"
import_article hw "The Hardware Renaissance"
import_article growth "Startup = Growth"
import_article swan "Black Swan Farming"
import_article todo "The Top of My Todo List"
import_article speak "Writing and Speaking"
import_article ycstart "How Y Combinator Started"
import_article property "Defining Property"
import_article ambitious "Frighteningly Ambitious Startup Ideas"
import_article word "A Word to the Resourceful"
import_article schlep "Schlep Blindness"
import_article vw "Snapshot: Viaweb, June 1998"
import_article hubs "Why Startup Hubs Work"
import_article patentpledge "The Patent Pledge"
import_article airbnb "Subject: Airbnb"
import_article control "Founder Control"
import_article tablets "Tablets"
import_article founders "What We Look for in Founders"
import_article superangels "The New Funding Landscape"
import_article seesv "Where to See Silicon Valley"
import_article hiresfund "High Resolution Fundraising"
import_article yahoo "What Happened to Yahoo"
import_article future "The Future of Startup Funding"
import_article addiction "The Acceleration of Addictiveness"
import_article top "The Top Idea in Your Mind"
import_article organic "Organic Startup Ideas"
import_article apple "Apple's Mistake"
import_article really "What Startups Are Really Like"
import_article discover "Persuade xor Discover"
import_article publishing "Post-Medium Publishing"
import_article nthings "The List of N Things"
import_article determination "The Anatomy of Determination"
import_article kate "What Kate Saw in Silicon Valley"
import_article segway "The Trouble with the Segway"
import_article ramenprofitable "Ramen Profitable"
import_article makersschedule "Maker's Schedule, Manager's Schedule"
import_article revolution "A Local Revolution?"
import_article twitter "Why Twitter is a Big Deal"
import_article foundervisa "The Founder Visa"
import_article 5founders "Five Founders"
import_article relres "Relentlessly Resourceful"
import_article angelinvesting "How to Be an Angel Investor"
import_article convergence "Why TV Lost"
import_article maybe "Can You Buy a Silicon Valley? Maybe."
import_article hackernews "What I've Learned from Hacker News"
import_article 13sentences "Startups in 13 Sentences"
import_article identity "Keep Your Identity Small"
import_article credentials "After Credentials"
import_article divergence "Could VC be a Casualty of the Recession?"
import_article highres "The High-Res Society"
import_article artistsship "The Other Half of \\\"Artists Ship\\\""
import_article badeconomy "Why to Start a Startup in a Bad Economy"
import_article fundraising "A Fundraising Survival Guide"
import_article prcmc "The Pooled-Risk Company Management Company"
import_article cities "Cities and Ambition"
import_article distraction "Disconnecting Distraction"
import_article lies "Lies We Tell Kids"
import_article good "Be Good"
import_article googles "Why There Aren't More Googles"
import_article heroes "Some Heroes"
import_article disagree "How to Disagree"
import_article boss "You Weren't Meant to Have a Boss"
import_article ycombinator "A New Venture Animal"
import_article trolls "Trolls"
import_article newthings "Six Principles for Making New Things"
import_article startuphubs "Why to Move to a Startup Hub"
import_article webstartups "The Future of Web Startups"
import_article philosophy "How to Do Philosophy"
import_article colleges "News from the Front"
import_article die "How Not to Die"
import_article head "Holding a Program in One's Head"
import_article stuff "Stuff"
import_article equity "The Equity Equation"
import_article unions "An Alternative Theory of Unions"
import_article guidetoinvestors "The Hacker's Guide to Investors"
import_article judgement "Two Kinds of Judgement"
import_article microsoft "Microsoft is Dead"
import_article notnot "Why to Not Not Start a Startup"
import_article foundersatwork "Learning from Founders"
import_article goodart "How Art Can Be Good"
import_article startupmistakes "The 18 Mistakes That Kill Startups"
import_article mit "A Student's Guide to Startups"
import_article investors "How to Present to Investors"
import_article copy "Copy What You Like"
import_article island "The Island Test"
import_article marginal "The Power of the Marginal"
import_article america "Why Startups Condense in America"
import_article siliconvalley "How to Be Silicon Valley"
import_article startuplessons "The Hardest Lessons for Startups to Learn"
import_article randomness "See Randomness"
import_article softwarepatents "Are Software Patents Evil?"
import_article 6631327 "6,631,372"
import_article whyyc "Why YC"
import_article love "How to Do What You Love"
import_article procrastination "Good and Bad Procrastination"
import_article web20 "Web 2.0"
import_article startupfunding "How to Fund a Startup"
import_article vcsqueeze "The Venture Capital Squeeze"
import_article ideas "Ideas for Startups"
import_article sfp "What I Did this Summer"
import_article inequality "Inequality and Risk"
import_article ladder "After the Ladder"
import_article opensource "What Business Can Learn from Open Source"
import_article hiring "Hiring is Obsolete"
import_article submarine "The Submarine"
import_article bronze "Why Smart People Have Bad Ideas"
import_article mac "Return of the Mac"
import_article writing44 "Writing, Briefly"
import_article college "Undergraduation"
import_article venturecapital "A Unified Theory of VC Suckage"
import_article start "How to Start a Startup"
import_article hs "What You'll Wish You'd Known"
import_article usa "Made in USA"
import_article charisma "It's Charisma, Stupid"
import_article polls "Bradley's Ghost"
import_article laundry "A Version 1.0"
import_article bubble "What the Bubble Got Right"
import_article essay "The Age of the Essay"
import_article pypar "The Python Paradox"
import_article gh "Great Hackers"
import_article gap "Mind the Gap"
import_article wealth "How to Make Wealth"
import_article gba "The Word \\\"Hacker\\\""
import_article say "What You Can't Say"
import_article ffb "Filters that Fight Back"
import_article hp "Hackers and Painters"
import_article iflisp "If Lisp is So Great"
import_article hundred "The Hundred-Year Language"
import_article nerds "Why Nerds are Unpopular"
import_article better "Better Bayesian Filtering"
import_article desres "Design and Research"
import_article spam "A Plan for Spam"
import_article power "Succinctness is Power"
import_article fix "What Languages Fix"
import_article diff "What Made Lisp Different"
import_article rootsoflisp "The Roots of Lisp"
import_article javacover "Java's Cover"
import_article lwba "Lisp for Web-Based Applications"
import_article prop62 "This Year We Can End the Death Penalty in California"
